# Generated by Django 6.0 on 2026-01-10 18:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("trading", "0014_strategy_asset_strategy_broker_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("STRATEGY", "Analyse de stratégie"),
                            ("PORTFOLIO", "Analyse de portefeuille"),
                            ("ASSET", "Analyse d'actif"),
                            ("MARKET", "Analyse de marché"),
                        ],
                        help_text="Type d'analyse effectuée",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("PROCESSING", "En cours"),
                            ("COMPLETED", "Terminée"),
                            ("FAILED", "Échouée"),
                        ],
                        default="PENDING",
                        help_text="Statut de l'analyse",
                        max_length=20,
                    ),
                ),
                ("prompt", models.TextField(help_text="Prompt envoyé à l'IA")),
                (
                    "response",
                    models.TextField(blank=True, help_text="Réponse brute de l'IA"),
                ),
                (
                    "summary",
                    models.TextField(blank=True, help_text="Résumé de l'analyse"),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        default=list, help_text="Liste de recommandations structurées"
                    ),
                ),
                (
                    "insights",
                    models.JSONField(
                        default=dict,
                        help_text="Insights clés extraits (métriques, tendances, etc.)",
                    ),
                ),
                (
                    "risks",
                    models.JSONField(default=list, help_text="Risques identifiés"),
                ),
                (
                    "opportunities",
                    models.JSONField(
                        default=list, help_text="Opportunités identifiées"
                    ),
                ),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Score de confiance de l'IA (0-100)",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Métadonnées additionnelles (version modèle, tokens utilisés, etc.)",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True, help_text="Message d'erreur en cas d'échec"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, help_text="Date de dernière modification"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date de complétion de l'analyse",
                        null=True,
                    ),
                ),
                (
                    "is_daily_report",
                    models.BooleanField(
                        default=False,
                        help_text="True si généré par le rapport quotidien automatique",
                    ),
                ),
                (
                    "is_archived",
                    models.BooleanField(
                        default=False, help_text="True si l'analyse est archivée"
                    ),
                ),
                (
                    "all_asset",
                    models.ForeignKey(
                        blank=True,
                        help_text="Actif analysé (si analysis_type=ASSET)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="trading.allassets",
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        help_text="Stratégie analysée (si analysis_type=STRATEGY)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to="trading.strategy",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Utilisateur propriétaire de l'analyse",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI Analysis",
                "verbose_name_plural": "AI Analyses",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "analysis_type", "-created_at"],
                        name="ai_assistan_user_id_0c0a70_idx",
                    ),
                    models.Index(
                        fields=["strategy", "-created_at"],
                        name="ai_assistan_strateg_8e724d_idx",
                    ),
                    models.Index(
                        fields=["status"], name="ai_assistan_status_31afd3_idx"
                    ),
                    models.Index(
                        fields=["is_daily_report", "-created_at"],
                        name="ai_assistan_is_dail_513a18_idx",
                    ),
                ],
            },
        ),
    ]
