# Generated by Django 6.0 on 2025-12-27 00:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("symbol", models.CharField(max_length=20, unique=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "asset_type",
                    models.CharField(
                        choices=[
                            ("STOCK", "Action"),
                            ("CRYPTO", "Cryptomonnaie"),
                            ("ETF", "ETF"),
                            ("FOREX", "Forex"),
                            ("COMMODITY", "Matière première"),
                            ("BOND", "Obligation"),
                            ("OTHER", "Autre"),
                        ],
                        default="STOCK",
                        max_length=20,
                    ),
                ),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("exchange", models.CharField(blank=True, max_length=50)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("price_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
                "ordering": ["symbol"],
            },
        ),
        migrations.CreateModel(
            name="Broker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "broker_type",
                    models.CharField(
                        choices=[
                            ("SAXO", "Saxo Bank"),
                            ("BINANCE", "Binance"),
                            ("IB", "Interactive Brokers"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("api_base_url", models.URLField(blank=True)),
                ("api_version", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("supports_stocks", models.BooleanField(default=True)),
                ("supports_crypto", models.BooleanField(default=False)),
                ("supports_forex", models.BooleanField(default=False)),
                ("supports_futures", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Broker",
                "verbose_name_plural": "Brokers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("SYNC_POSITIONS", "Sync Positions"),
                            ("SYNC_TRADES", "Sync Trades"),
                            ("SYNC_PRICES", "Sync Prix"),
                            ("SYNC_ASSETS", "Sync Assets"),
                            ("REFRESH_TOKENS", "Refresh Tokens"),
                            ("CUSTOM", "Personnalisée"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("CRON", "Cron"),
                            ("INTERVAL", "Intervalle"),
                            ("ONE_TIME", "Une fois"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "cron_expression",
                    models.CharField(
                        blank=True,
                        help_text="Ex: 0 */15 * * * (toutes les 15 min)",
                        max_length=100,
                    ),
                ),
                (
                    "interval_minutes",
                    models.IntegerField(
                        blank=True, help_text="Intervalle en minutes", null=True
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("next_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Scheduled Task",
                "verbose_name_plural": "Scheduled Tasks",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BrokerAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("account_id", models.CharField(max_length=100)),
                ("account_name", models.CharField(blank=True, max_length=100)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("balance_updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_demo", models.BooleanField(default=False)),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accounts",
                        to="trading.broker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="broker_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Account",
                "verbose_name_plural": "Broker Accounts",
                "ordering": ["broker__name"],
                "unique_together": {("user", "broker", "account_id")},
            },
        ),
        migrations.CreateModel(
            name="BrokerSyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("POSITIONS", "Positions"),
                            ("TRADES", "Trades"),
                            ("ORDERS", "Ordres"),
                            ("BALANCE", "Balance"),
                            ("ASSETS", "Assets"),
                            ("PRICES", "Prix"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Succès"),
                            ("PARTIAL", "Partiel"),
                            ("FAILED", "Échec"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_synced", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "broker_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_logs",
                        to="trading.brokeraccount",
                    ),
                ),
            ],
            options={
                "verbose_name": "Broker Sync Log",
                "verbose_name_plural": "Broker Sync Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order_type",
                    models.CharField(
                        choices=[
                            ("MARKET", "Market"),
                            ("LIMIT", "Limit"),
                            ("STOP", "Stop"),
                            ("STOP_LIMIT", "Stop Limit"),
                        ],
                        default="MARKET",
                        max_length=20,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[("BUY", "Achat"), ("SELL", "Vente")], max_length=10
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "En attente"),
                            ("OPEN", "Ouvert"),
                            ("FILLED", "Exécuté"),
                            ("PARTIALLY_FILLED", "Partiellement exécuté"),
                            ("CANCELLED", "Annulé"),
                            ("REJECTED", "Rejeté"),
                            ("EXPIRED", "Expiré"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "filled_quantity",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "stop_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("broker_order_id", models.CharField(blank=True, max_length=100)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.asset",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to="trading.broker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Order",
                "verbose_name_plural": "Orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Strategy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("LOW", "Faible"),
                            ("MEDIUM", "Moyen"),
                            ("HIGH", "Élevé"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                    ),
                ),
                (
                    "max_position_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Taille maximale d'une position en %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "max_daily_loss",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Perte maximale journalière en %",
                        max_digits=10,
                        null=True,
                    ),
                ),
                ("parameters", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_automated", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="strategies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy",
                "verbose_name_plural": "Strategies",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "side",
                    models.CharField(
                        choices=[("LONG", "Long"), ("SHORT", "Short")],
                        default="LONG",
                        max_length=10,
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("entry_price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "current_price",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "stop_loss",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                (
                    "take_profit",
                    models.DecimalField(
                        blank=True, decimal_places=8, max_digits=20, null=True
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("opened_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading.asset",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to="trading.broker",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="positions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="positions",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Position",
                "verbose_name_plural": "Positions",
                "ordering": ["-opened_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("RUNNING", "En cours"),
                            ("SUCCESS", "Succès"),
                            ("FAILED", "Échec"),
                            ("CANCELLED", "Annulée"),
                        ],
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField()),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("duration_seconds", models.FloatField(blank=True, null=True)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="execution_logs",
                        to="trading.scheduledtask",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Execution Log",
                "verbose_name_plural": "Task Execution Logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Trade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "trade_type",
                    models.CharField(
                        choices=[("BUY", "Achat"), ("SELL", "Vente")], max_length=10
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=8, max_digits=20)),
                ("price", models.DecimalField(decimal_places=8, max_digits=20)),
                (
                    "fees",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("executed_at", models.DateTimeField()),
                ("broker_trade_id", models.CharField(blank=True, max_length=100)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading.asset",
                    ),
                ),
                (
                    "broker",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to="trading.broker",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trades",
                        to="trading.position",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trades",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Trade",
                "verbose_name_plural": "Trades",
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="AssetPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("open_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("high_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("low_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("close_price", models.DecimalField(decimal_places=8, max_digits=20)),
                ("volume", models.BigIntegerField(blank=True, null=True)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="trading.asset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asset Price",
                "verbose_name_plural": "Asset Prices",
                "ordering": ["-date"],
                "unique_together": {("asset", "date")},
            },
        ),
        migrations.CreateModel(
            name="StrategyPerformance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("total_trades", models.IntegerField(default=0)),
                ("winning_trades", models.IntegerField(default=0)),
                ("losing_trades", models.IntegerField(default=0)),
                (
                    "gross_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "fees",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "net_pnl",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performances",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Performance",
                "verbose_name_plural": "Strategy Performances",
                "ordering": ["-date"],
                "unique_together": {("strategy", "date")},
            },
        ),
    ]
