# Generated by Django 6.0 on 2025-12-27 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="dividend_yield",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="asset",
            name="market_cap",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="pe_ratio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="sector",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name="AllAssets",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("symbol", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("SAXO", "Saxo Bank"),
                            ("BINANCE", "Binance"),
                            ("IB", "Interactive Brokers"),
                            ("OTHER", "Autre"),
                        ],
                        max_length=20,
                    ),
                ),
                ("asset_type", models.CharField(max_length=50)),
                ("market", models.CharField(max_length=50)),
                ("currency", models.CharField(default="USD", max_length=10)),
                ("exchange", models.CharField(blank=True, max_length=100)),
                ("is_tradable", models.BooleanField(default=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("saxo_uic", models.IntegerField(blank=True, null=True)),
                ("saxo_exchange_id", models.CharField(blank=True, max_length=20)),
                ("saxo_country_code", models.CharField(blank=True, max_length=10)),
                ("binance_base_asset", models.CharField(blank=True, max_length=20)),
                ("binance_quote_asset", models.CharField(blank=True, max_length=20)),
                ("binance_status", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "All Asset",
                "verbose_name_plural": "All Assets",
                "indexes": [
                    models.Index(
                        fields=["platform", "asset_type"],
                        name="trading_all_platfor_91a5d4_idx",
                    ),
                    models.Index(
                        fields=["symbol"], name="trading_all_symbol_b11934_idx"
                    ),
                    models.Index(fields=["name"], name="trading_all_name_8842c2_idx"),
                ],
                "unique_together": {("symbol", "platform")},
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="all_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Référence vers le catalogue universel des actifs",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enriched_assets",
                to="trading.allassets",
            ),
        ),
    ]
