# Generated by Django 6.0 on 2025-12-27 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading",
            "0002_asset_dividend_yield_asset_industry_asset_market_cap_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="brokersynclog",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Broker Sync Log",
                "verbose_name_plural": "Broker Sync Logs",
            },
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="api_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="api_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="client_id",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="client_secret",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="extra_credentials",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="is_sandbox",
            field=models.BooleanField(
                default=True, help_text="Use sandbox/simulation environment"
            ),
        ),
        migrations.AddField(
            model_name="brokersynclog",
            name="details",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="brokersynclog",
            name="records_synced",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="brokersynclog",
            name="started_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="brokersynclog",
            name="status",
            field=models.CharField(
                choices=[
                    ("SUCCESS", "Succès"),
                    ("PARTIAL", "Partiel"),
                    ("FAILED", "Échec"),
                    ("ERROR", "Erreur"),
                    ("WARNING", "Avertissement"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="brokersynclog",
            name="sync_type",
            field=models.CharField(max_length=50),
        ),
    ]
