# Generated by Django 6.0 on 2025-12-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0003_alter_brokersynclog_options_brokeraccount_api_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allassets",
            name="symbole_yahoo",
            field=models.CharField(
                db_index=True,
                default="Not_searched",
                help_text="Symbole Yahoo validé, 'not_found', 'manual', ou 'Not_searched'",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="allassets",
            name="yahoo_validated_at",
            field=models.DateTimeField(
                blank=True, help_text="Date de dernière validation Yahoo", null=True
            ),
        ),
        migrations.AddField(
            model_name="allassets",
            name="yahoo_validation_method",
            field=models.CharField(
                blank=True,
                help_text="Méthode de validation: Y4 (MIC), Y3 (nom), Y0 (brut)",
                max_length=20,
            ),
        ),
    ]
