# Generated by Django 6.0 on 2025-12-27 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0004_add_yahoo_fields_to_allassets"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        # D'abord, ajouter tous les nouveaux champs
        migrations.AddField(
            model_name="brokeraccount",
            name="name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Nom pour identifier cette configuration (ex: 'Mon compte Saxo principal')",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="broker_type",
            field=models.CharField(
                choices=[
                    ("SAXO", "Saxo Bank"),
                    ("BINANCE", "Binance"),
                    ("IB", "Interactive Brokers"),
                    ("OTHER", "Autre"),
                ],
                default="OTHER",
                help_text="Type de broker (Saxo, Binance, etc.)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="auto_refresh_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Activer le rafraîchissement automatique des tokens",
                verbose_name="Auto-refresh activé",
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="auto_refresh_frequency",
            field=models.IntegerField(
                default=45,
                help_text="Fréquence en minutes (15-55 min)",
                verbose_name="Fréquence auto-refresh (minutes)",
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="binance_api_key",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="binance_api_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="binance_testnet",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="environment",
            field=models.CharField(
                choices=[("live", "Live Trading"), ("simulation", "Simulation/Demo")],
                default="simulation",
                help_text="Environnement de trading (Live ou Simulation)",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="last_sync",
            field=models.DateTimeField(
                blank=True, help_text="Dernière synchronisation", null=True
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_access_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_client_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_client_secret",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_environment",
            field=models.CharField(
                choices=[("live", "Live"), ("simulation", "Simulation")],
                default="simulation",
                max_length=20,
                verbose_name="Environnement Saxo",
            ),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_redirect_uri",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="brokeraccount",
            name="saxo_token_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="account_id",
            field=models.CharField(
                blank=True, help_text="ID du compte chez le broker", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="broker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accounts",
                to="trading.broker",
            ),
        ),
        migrations.RemoveField(
            model_name="brokeraccount",
            name="account_name",
        ),
        # Ensuite, modifier les options et contraintes une fois que les champs existent
        migrations.AlterModelOptions(
            name="brokeraccount",
            options={
                "ordering": ["broker_type", "name"],
                "verbose_name": "Broker Account",
                "verbose_name_plural": "Broker Accounts",
            },
        ),
        migrations.AlterUniqueTogether(
            name="brokeraccount",
            unique_together={("user", "broker_type", "name")},
        ),
    ]
