# Generated by Django 6.0 on 2025-12-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0005_alter_brokeraccount_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="brokersynclog",
            name="error_message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
