# Generated by Django 6.0 on 2026-01-01 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0009_add_all_asset_price_history"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="allassetpricehistory",
            new_name="trading_all_all_ass_0a2a03_idx",
            old_name="trading_all_all_asse_idx",
        ),
        migrations.RenameIndex(
            model_name="allassetpricehistory",
            new_name="trading_all_all_ass_c15805_idx",
            old_name="trading_all_all_asse_idx_desc",
        ),
        migrations.AddField(
            model_name="allassets",
            name="price_history_days",
            field=models.IntegerField(
                default=0, help_text="Nombre de jours d'historique stockés"
            ),
        ),
        migrations.AddField(
            model_name="allassets",
            name="price_history_json",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Historique des prix au format JSON: {'YYYY-MM-DD': {'open': x, 'high': y, 'low': z, 'close': w, 'volume': v, 'source': 'YAHOO'}, ...}",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="allassets",
            name="price_history_updated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date de dernière mise à jour de l'historique des prix",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="environment",
            field=models.CharField(
                choices=[("live", "Live Trading"), ("simulation", "Simulation/Demo")],
                default="live",
                help_text="Environnement de trading (Live ou Simulation)",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="brokeraccount",
            name="saxo_environment",
            field=models.CharField(
                choices=[("live", "Live"), ("simulation", "Simulation")],
                default="live",
                max_length=20,
                verbose_name="Environnement Saxo",
            ),
        ),
    ]
