# Generated by Django 6.0 on 2026-01-02 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0010_add_price_history_jsonb"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="all_asset",
            field=models.ForeignKey(
                help_text="Asset cible que cette stratégie trade",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="strategies",
                to="trading.allassets",
            ),
        ),
        migrations.AddIndex(
            model_name="strategy",
            index=models.Index(
                fields=["all_asset", "is_active"], name="trading_str_all_ass_b0e29f_idx"
            ),
        ),
    ]
