# Generated by Django 6.0 on 2026-01-02 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0011_add_all_asset_to_strategy"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="all_asset",
            field=models.ForeignKey(
                help_text="Asset depuis le catalogue universel AllAssets (nom exact du broker)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="trading.allassets",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset enrichi optionnel (pour données supplémentaires)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="trading.asset",
            ),
        ),
    ]
