# Generated by Django 6.0 on 2026-01-02 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0012_add_all_asset_to_order"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlgorithmSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "algorithm_type",
                    models.CharField(
                        help_text="Type d'algorithme (threshold, rsi, etc.)",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nom affiché de l'algorithme", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description de l'algorithme"
                    ),
                ),
            ],
            options={
                "verbose_name": "Algorithm Schema",
                "verbose_name_plural": "Algorithm Schemas",
                "ordering": ["algorithm_type"],
            },
        ),
        migrations.AddField(
            model_name="strategy",
            name="algorithm_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("threshold", "Threshold"),
                    ("ma_crossover", "Moving Average Crossover"),
                    ("rsi", "RSI"),
                    ("bollinger", "Bollinger Bands"),
                    ("macd", "MACD"),
                    ("grid", "Grid Trading"),
                ],
                help_text="Type d'algorithme de trading",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="parameters",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Paramètres (ancien système - utilisé en fallback)",
            ),
        ),
        migrations.CreateModel(
            name="AlgorithmParameter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(help_text="Clé du paramètre", max_length=100)),
                (
                    "value",
                    models.TextField(
                        help_text="Valeur du paramètre (stockée en string)"
                    ),
                ),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("str", "String"),
                            ("bool", "Boolean"),
                        ],
                        help_text="Type de données du paramètre",
                        max_length=10,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Description du paramètre", max_length=255
                    ),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="algorithm_parameters",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Algorithm Parameter",
                "verbose_name_plural": "Algorithm Parameters",
                "ordering": ["key"],
                "indexes": [
                    models.Index(
                        fields=["strategy", "key"],
                        name="trading_alg_strateg_23bcf6_idx",
                    )
                ],
                "unique_together": {("strategy", "key")},
            },
        ),
        migrations.CreateModel(
            name="AlgorithmParameterDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(help_text="Clé du paramètre", max_length=100)),
                (
                    "param_type",
                    models.CharField(
                        choices=[
                            ("int", "Integer"),
                            ("float", "Float"),
                            ("str", "String"),
                            ("bool", "Boolean"),
                        ],
                        help_text="Type de données du paramètre",
                        max_length=10,
                    ),
                ),
                (
                    "default_value",
                    models.TextField(blank=True, help_text="Valeur par défaut"),
                ),
                (
                    "required",
                    models.BooleanField(
                        default=True, help_text="Paramètre obligatoire"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, help_text="Description du paramètre", max_length=255
                    ),
                ),
                (
                    "min_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Valeur minimale",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "max_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Valeur maximale",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parameter_definitions",
                        to="trading.algorithmschema",
                    ),
                ),
            ],
            options={
                "verbose_name": "Algorithm Parameter Definition",
                "verbose_name_plural": "Algorithm Parameter Definitions",
                "ordering": ["key"],
                "unique_together": {("schema", "key")},
            },
        ),
    ]
