# Generated by Django 6.0 on 2026-01-02 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0013_algorithmschema_strategy_algorithm_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Budget alloué à cette stratégie",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="max_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Quantité maximale d'achat",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="min_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Quantité minimale d'achat (1 pour actions, 0.0005 pour crypto)",
                max_digits=20,
                null=True,
            ),
        ),
    ]
