# Generated by Django 6.0 on 2026-01-10 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0013_algorithmschema_strategy_algorithm_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset Saxo spécifique (optionnel)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategies",
                to="trading.asset",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="broker_account",
            field=models.ForeignKey(
                blank=True,
                help_text="Compte broker pour exécuter cette stratégie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategies",
                to="trading.brokeraccount",
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="budget",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Budget alloué à cette stratégie",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="check_frequency",
            field=models.IntegerField(
                default=45, help_text="Fréquence de vérification en minutes"
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("simulation", "Simulation"),
                    ("paper_trading", "Paper Trading"),
                    ("live_trading", "Trading Réel"),
                ],
                default="simulation",
                help_text="Mode d'exécution de la stratégie",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="max_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Quantité maximale d'achat",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="min_quantity",
            field=models.DecimalField(
                blank=True,
                decimal_places=10,
                help_text="Quantité minimale d'achat (1 pour actions, 0.0005 pour crypto)",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="strategy",
            name="portfolio_quantity",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                help_text="Quantité actuellement détenue en portefeuille",
                max_digits=20,
            ),
        ),
    ]
