# Generated by Django 6.0 on 2026-01-10 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0014_strategy_asset_strategy_broker_account_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Stratégie ayant généré cet ordre",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="trading.strategy",
            ),
        ),
        migrations.AddField(
            model_name="trade",
            name="strategy",
            field=models.ForeignKey(
                blank=True,
                help_text="Stratégie ayant généré ce trade",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trades",
                to="trading.strategy",
            ),
        ),
    ]
