# Generated by Django 6.0 on 2026-01-12 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0016_portfoliosnapshot"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="max_daily_loss",
        ),
        migrations.RemoveField(
            model_name="strategy",
            name="max_position_size",
        ),
    ]
