# Generated by Django 6.0 on 2026-01-17 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0017_remove_strategy_max_daily_loss_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allassets",
            name="is_best_variant",
            field=models.BooleanField(
                default=False,
                help_text="Indique si c'est la meilleure variante pour le parent_asset (USD prioritaire)",
            ),
        ),
        migrations.AddField(
            model_name="allassets",
            name="parent_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Asset normalisé parent (ex: AAPL pour AAPL:xnas, AAPL:xnys)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="trading.asset",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="best_variant",
            field=models.ForeignKey(
                blank=True,
                help_text="Meilleur AllAssets pour trading (USD, NYSE/NASDAQ prioritaires)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="trading.allassets",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="all_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="[DEPRECATED] Utiliser best_variant à la place",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enriched_assets",
                to="trading.allassets",
            ),
        ),
        migrations.AlterField(
            model_name="asset",
            name="symbol",
            field=models.CharField(
                help_text="Symbole normalisé sans MIC (ex: AAPL, BTC, ETH)",
                max_length=50,
                unique=True,
            ),
        ),
    ]
