# Generated by Django 6.0 on 2026-01-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0018_allassets_is_best_variant_allassets_parent_asset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="is_favorite",
            field=models.BooleanField(
                default=False, help_text="Asset ajouté manuellement à la watchlist"
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="is_tracked",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Asset suivi (a des trades/positions ou ajouté manuellement)",
            ),
        ),
    ]
