# Generated by Django 6.0 on 2026-01-17 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0019_asset_is_favorite_asset_is_tracked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="strategy",
            name="broker_account",
            field=models.ForeignKey(
                help_text="Compte broker pour exécuter cette stratégie",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="strategies",
                to="trading.brokeraccount",
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="budget",
            field=models.DecimalField(
                decimal_places=2,
                default=1000,
                help_text="Budget alloué à cette stratégie",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="execution_mode",
            field=models.CharField(
                choices=[
                    ("simulation", "Simulation"),
                    ("paper_trading", "Paper Trading"),
                    ("live_trading", "Trading Réel"),
                ],
                default="live_trading",
                help_text="Mode d'exécution de la stratégie",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="is_active",
            field=models.BooleanField(default=True, help_text="Stratégie active"),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="is_automated",
            field=models.BooleanField(
                default=True, help_text="Trading automatique activé"
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="max_quantity",
            field=models.DecimalField(
                decimal_places=10,
                default=1,
                help_text="Quantité maximale d'achat",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="strategy",
            name="min_quantity",
            field=models.DecimalField(
                decimal_places=10,
                default=0,
                help_text="Quantité minimale d'achat",
                max_digits=20,
            ),
        ),
    ]
