# Generated by Django 6.0 on 2026-01-17 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trading",
            "0020_alter_strategy_broker_account_alter_strategy_budget_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="strategy",
            name="stop_loss_percentage",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Pourcentage de stop-loss par trade (ex: 5.00 pour 5%)",
                max_digits=5,
                null=True,
            ),
        ),
    ]
