# Generated by Django 6.0 on 2026-01-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0021_strategy_stop_loss_percentage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="strategy",
            name="stop_loss_percentage",
        ),
    ]
