# Generated by Django 6.0 on 2026-01-19 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0022_remove_strategy_stop_loss_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="StrategyExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "En cours"),
                            ("completed", "Terminé"),
                            ("failed", "Échoué"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                (
                    "signal",
                    models.CharField(
                        choices=[
                            ("BUY", "Achat"),
                            ("SELL", "Vente"),
                            ("HOLD", "Conserver"),
                            ("NONE", "Aucun signal"),
                        ],
                        default="NONE",
                        max_length=10,
                    ),
                ),
                (
                    "signal_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Prix au moment du signal",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "signal_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=10,
                        help_text="Quantité recommandée",
                        max_digits=20,
                        null=True,
                    ),
                ),
                (
                    "output",
                    models.TextField(
                        blank=True, help_text="Détails de l'exécution (JSON)"
                    ),
                ),
                (
                    "error",
                    models.TextField(blank=True, help_text="Message d'erreur si échec"),
                ),
                (
                    "strategy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="executions",
                        to="trading.strategy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Strategy Execution",
                "verbose_name_plural": "Strategy Executions",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["-started_at"], name="trading_str_started_bfc236_idx"
                    ),
                    models.Index(
                        fields=["strategy", "-started_at"],
                        name="trading_str_strateg_d08f63_idx",
                    ),
                ],
            },
        ),
    ]
