# Generated by Django 6.0 on 2026-04-30 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0023_strategyexecution"),
    ]

    operations = [
        migrations.AddField(
            model_name="allassets",
            name="industry",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
        migrations.AddField(
            model_name="allassets",
            name="sector",
            field=models.CharField(blank=True, default="", max_length=150),
        ),
    ]
