# Generated by GPT-5.2 on 2026-05-06

from django.db import migrations, models
import django.db.models.deletion


def delete_orders_without_all_asset(apps, schema_editor):
    Order = apps.get_model("trading", "Order")
    # Supprime les ordres existants sans AllAsset, avant d'appliquer la contrainte NOT NULL.
    Order.objects.filter(all_asset__isnull=True).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("trading", "0025_strategy_portfolio_bounds"),
    ]

    operations = [
        migrations.RunPython(delete_orders_without_all_asset, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="order",
            name="all_asset",
            field=models.ForeignKey(
                help_text="Asset depuis le catalogue universel AllAssets (nom exact du broker)",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="trading.allassets",
            ),
        ),
    ]

