# Generated by Django 5.2.13 on 2026-08-24 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading", "0026_order_all_asset_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TransactionCost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "commission",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "exchange_fee",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "spread_cost",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "financing_cost",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=8, default=0, max_digits=20),
                ),
                ("currency", models.CharField(default="EUR", max_length=10)),
                ("is_estimate", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("precheck", "Precheck"),
                            ("report", "Report"),
                            ("trading_conditions", "Trading conditions"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "saxo_trade_id",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("uic", models.IntegerField(blank=True, null=True)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("fetched_at", models.DateTimeField()),
                (
                    "trade",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_costs",
                        to="trading.trade",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transaction_costs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction cost",
                "verbose_name_plural": "Transaction costs",
                "ordering": ["-fetched_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("trade__isnull", False)),
                        fields=("trade", "source"),
                        name="uniq_transaction_cost_trade_source",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("saxo_trade_id", ""), _negated=True),
                        fields=("saxo_trade_id", "source"),
                        name="uniq_transaction_cost_saxo_trade_source",
                    ),
                ],
            },
        ),
    ]
